@startuml

' use strict UML mode
skinparam style strictuml

actor "User" as user

' create main adminstration 
participant "Administration" as main <<main>>
main++

' create main menu frame
create "MainMenu" as menu <<frame>>
main -> menu : construct

user -> menu++ : clicks 'Add New Product' button

' create product editor dialog
create "ProductEditor" as editor <<dialog>>
menu -> editor : construct

' activate editor constructor
editor++

' create a DAO
create "ProductListDAO" as dao <<DAO>>
editor -> dao : construct 
editor--

' user enters product details and clicks the save product button
user -> editor++ : enters product details
editor--
user -> editor++ : clicks 'Save' button

editor -> editor : get product details from multiple GUI components
editor -> editor : convert number values from String to BigDecimal and Integer

' create a Product
create "Product" as product <<domain>>
editor -> product : construct

editor -> product++ : set multiple fields using setters
product-- 

editor -> product++ : System.out.println(product)
product--

editor -> dao++ : save(product)
dao--

' dispose dialog
user -> editor++ : clicks 'Cancel' button
editor -> editor : dispose()
destroy editor

@enduml
